# factory/tasks/_clean.yml
version: '3'
tasks:
  clean:
    desc: "Removes all local temporary files and build artifacts (node_modules, context files)."
    silent: true
    cmds:
      - ./factory/scripts/clean.sh
