# factory/tasks/_destroy.yml
version: '3'
tasks:
  destroy:
    desc: "(Info) This task is not applicable to Apps Script projects."
    silent: true
    cmds:
      - echo "INFO - The 'destroy' command is not used in this Apps Script project."
