# factory/tasks/_run.yml
version: '3'
tasks:
  run:
    desc: "(Info) This task is not applicable to Apps Script projects."
    silent: true
    cmds:
      - echo "INFO - The 'run' command is not used in this Apps Script project."
