# factory/tasks/_task-start.yml
version: '3'
tasks:
  task-start:
    desc: "(Placeholder) Task to be implemented for task-start."
    silent: true
    cmds:
      - echo "INFO - The 'task-start' task is a placeholder and needs to be implemented."
