# factory/tasks/_task-start.yml
version: '3'

tasks:
  task-start:
    desc: "Interactively creates and checks out a new, conventional feature branch."
    silent: true
    cmds:
      - ./factory/scripts/start_task.sh
